### PR TITLE
Compatibility with R1

### PR DESCRIPTION
**Pull request by szagoruyko**
cherry picked 2 commits from R1 and added padW and padH check to Pooling.lua, that's all.

### CODE REVIEW

**Comment by soumith** [comment]
great!

**Comment by soumith** [comment]
ok the only thing that;s out of sync with R1 seems to be the Average Pooling tests, which does not matter much, i will pull it when i get time

**Comment by soumith** [comment]
are you guys switching to R2, now that the bugs have been fixed by NVIDIA?

**Comment by szagoruyko** [comment]
definitely switching!

**Comment by soumith** [comment]
ok if you dont have any trouble with it for 1 week, i will switch master to be RC2 and reflect everything accurately.

**Comment by soumith** [comment]
NVIDIA also sent me a mail saying that MaxPooling is now fixed!

**Comment by szagoruyko** [comment]
I've been testing it today, haven't found any issues so far. Really like this version and the bindings!

**Pull request merged**
