### PR TITLE
patch RNN.lua for Windows

### PR DESCRIPTION
**Pull request by elikosan**
same patch as in find.lua:
see https://github.com/soumith/cudnn.torch/commit/8903d1b389e49175de0493e9507306c7be89612f

### CODE REVIEW

**Comment by BTNC** [comment]
Thank you! Could you please also patch init.lua?

**Comment by soumith** [comment]
thanks!

**Comment by elikosan** [comment]
Hi @BTNC, i don't think init.lua does  require a patch since the LongTensor are converted to IntTensor with :int(). 

   local size = torch.LongTensor(t:size()):int()

**Comment by BTNC** [comment]
Hi @elikosan , you are right, thanks again!

**Comment by F0REacH** [comment]
Encountered error. Looks like conflict with this PR #309 and PR #240
Using `LuaJIT 2.1.0-beta1`
```
/home/foreach/SOFT/TORCH/distro/install/bin/luajit: invalid arguments: number 
expected arguments: [*CudaTensor*] CudaTensor
stack traceback:
	[C]: at 0x7fa4bb7eadb0
	[C]: in function 'floor'
	...ch/SOFT/TORCH/distro/install/share/lua/5.1/cudnn/RNN.lua:63: in function 'reset'
	...ch/SOFT/TORCH/distro/install/share/lua/5.1/cudnn/RNN.lua:41: in function '__init'
	...ch/SOFT/TORCH/distro/install/share/lua/5.1/cudnn/GRU.lua:4: in function '__init'
	...h/SOFT/TORCH/distro/install/share/lua/5.1/torch/init.lua:91: in function <...h/SOFT/TORCH/distro/install/share/lua/5.1/torch/init.lua:87>
```
Fix was to change from `torch.floor` to `math.floor` in PR #240

**Comment by soumith** [comment]
@F0REacH for some reason, are you setting torch.setdefaulttensortype('torch.CudaTensor') ?

**Comment by F0REacH** [comment]
@soumith Yes.

**Comment by soumith** [comment]
@F0REacH if you do that, this error will be the first of your problems. Please dont set your default tensor type to CUDA tensor. it's not recommended or tested.

**Comment by F0REacH** [comment]
@soumith OK. Thanks for clarification.

**Pull request merged**
