### PR TITLE
use cudnn for temporal convolution

### PR DESCRIPTION
**Pull request by ngimel**
This speeds up temporal convolution 5 - 10 x, and requires a little extra space (nOutputFrames x outputFrameSize). I don't really like that TemporalConvolution inherits from SpatialConvolution, but otherwise there would be a lot of code duplication.

### CODE REVIEW

**Comment by szagoruyko** [comment]
you can inherit from `nn.TemporalConvolution` and call `cudnn.SpatialConvolution.updateOutput(self,input)` instead of `parent.updateOutput(self,input)` to avoid code duplication.

**Comment by soumith** [comment]
@szagoruyko what code duplication?

**Comment by ngimel** [comment]
@soumith - pretty much all SpatialConvolution.lua would have to be duplicated in TemporalConvolution, where now I just call parent functions. If/when cudnn interface changes, those changes will have to be applied everywhere.
@szagoruyko - thanks, I'll do that.

**Comment by soumith** [comment]
Thanks Natalia!

**Pull request merged**
