### PR TITLE
Added VolumetricBatchNormalization

### PR DESCRIPTION
**Pull request by misko**
The CUDNN R4 doc says batch normalization takes both 4D and 5D. Confirmed with NVIDIA that correct mode is CUDNN_BATCHNORM_SPATIAL for 3D batch normalization then copied and modified the SpatialBatchNormalization.lua. Also changed the bias vector size to match 3D.

### CODE REVIEW

**Comment by ngimel** [comment]
You can call cudnn.SpatialBatchNormalization.XXX functions instead of copy-pasting them.

**Comment by misko** [comment]
There is an assert for 4D tensor in the SpatialBatchNormalization that doesn't work with 5D tensor. Also the bias vector needs a different view and the 5th size dimension is not checked to match in SpatialBatchNormalization:createIODescriptors. 

SpatialBatchNormalization could be modified to support 5D tensors. Is this the preferred method? or is it to keep the spatial and volumetric functions in separate files?

**Comment by soumith** [comment]
@misko small changes are now needed to account for changes in API in 4.0.5.
See https://github.com/soumith/cudnn.torch/pull/101 for details.

**Comment by soumith** [comment]
actually, forget #101 , we reverted it. no further changes needed on this PR.

**Comment by misko** [comment]
I don't have a copy of the RCv4 API around, but I think some at least one of the calls changed, cudnnBatchNormalizationBackward. This seems to work now with R4 proper.

**Comment by soumith** [comment]
closed via https://github.com/soumith/cudnn.torch/pull/124

**Pull request closed without merging**
