### PR TITLE
lowered cuda dependency; there is no requirement for 7.5

### PR DESCRIPTION
**Pull request by lukasc-ch**
Removes the cmake dependency on CUDA 7.5. There is no actual dependency and it prevents installation on the Tegra X1, which only supports 7.0 but supports cuDNN R5.

### CODE REVIEW

**Comment by albanD** [comment]
It seems to me that cudnn R5 requires CUDA 7.5. On the download page of cudnn it says that only cudnn R4 is available for CUDA 7.0.

Is cudnn R5 actually supported with CUDA 7.0 for other cards than the Tegra X1 ? because @ngimel actually made a commit to add this requirement in #193.

**Comment by soumith** [comment]
I think the RNN parts require 7.5

After installing with 7.0, run:
https://github.com/soumith/cudnn.torch/blob/master/test/test_rnn.lua

it probably will fail.

**Comment by ngimel** [comment]
R5 is supported with CUDA 7.0 only on Tegra X1. There were several issues with people trying to run cudnn v5 with CUDA 7.0 driver and running into errors, so I made this commit.

**Comment by ngimel** [comment]
@soumith, it's not cuda toolkit version, it's the driver version. cudnn v5 requires driver corresponding to 7.5.

**Comment by lukasc-ch** [comment]
So if there is no CUDA 7.5 dependency, maybe we can remove it and instead add a runtime check for the correct driver version?

**Comment by lukasc-ch** [comment]
@ngimel Is it sufficient to require driver version >=7000? That's the version with which it runs on my X1 board.

**Comment by ngimel** [comment]
It's sufficient for X1 but insufficient for everything else (everything else needs 7.5 or even 8.0, depending on cudnn build, as it says on the downloads page)

**Comment by lukasc-ch** [comment]
added driver check at runtime with required version depending on the device.

**Comment by lukasc-ch** [comment]
@ngimel Do you still see any potential issues with the current PR?

**Comment by ngimel** [comment]
Looks good, thanks!

**Comment by szagoruyko** [comment]
@lukasc-ch can you add a check if cutorch has the `driverVersion` field to handle the case when you update cudnn with cutorch behind (which is very likely)

**Comment by lukasc-ch** [comment]
@szagoruyko good thinking :) added it.

**Comment by soumith** [comment]
Thanks Lukas!

**Pull request merged**
