### PR TITLE
fix for V5 GA RNN APIs

### PR DESCRIPTION
**Pull request by borisfom**
CUDNN5 GA has changes in some APIs. This fix is required to make GA work (it rejects RC for same reason).

### CODE REVIEW

**Comment by soumith** [comment]
All the tests seem to pass without this fix too. Does that mean that this codepath doesn't have any tests?

**Comment by borisfom** [comment]
Tests are in tests_rnn.lua. They are long so we did not merge them into test.lua.

**Comment by soumith** [comment]
ohk cool

**Comment by nicholas-leonard** [comment]
@borisfom Thanks this fixes my bug :)

**Pull request merged**
