### PR TITLE
Groups option with test againt ccn2

### PR DESCRIPTION
**Pull request by szagoruyko**
Happy New Year! It will be trivial to port it to R2

### CODE REVIEW

**Comment by szagoruyko** [comment]
how did you load it? loadcaffe cannot handle it's structure

**Comment by soumith** [comment]
maybe you have to update the caffe.proto because i see a few new modules in  there

**Comment by szagoruyko** [comment]
The problem is loadcaffe only handles sequential nets and can't load complex concat nets as GoogleNet. It could be done by exporting top and bottom names for each module and then running some graph connecting algorithm.. Another way is to fix deploy.prototxt.lua by hand just for GoogleNet.

**Comment by szagoruyko** [comment]
but 152 modules ughhh

**Comment by soumith** [comment]
ah i see. i'd just say it's not worth the effort. we have the googlenet lua implementation, i have to cut down the memory quite a bit using in-place ReLU and more free zero-padding (for pooling as well?) as appropriate.

**Comment by soumith** [comment]
i cant believe it is 2000 lines just writing down the model. i remember eblearn all over again, the "config file" thing is so inefficient, our spec is about 60 lines :-/  (I ahve to add a couple more branches, but i'll say another 60 lines tops)
https://github.com/soumith/convnet-benchmarks/blob/master/torch7/imagenet_winners/googlenet.lua

**Comment by szagoruyko** [comment]
indeed.. so I can take this and assign names corresponding to modules in prototxt to use loadcaffe to load weights, shouldn't take much time. Can we add in place relu to cudnn?

**Comment by soumith** [comment]
yea let me add in-place ReLU today. i have to make sure i am not doing something stupid.

**Comment by soumith** [comment]
ok with in-place ReLU, Googlenet works even on my Titan card (with batch-size 128!!! w00t).
I did not add the auxillary branch classifiers, i.e. branches 2 and 3, and that might just tip the memory limit over for a titan at batch-size 128, but at batch-size 64, it should fit quite comfortably.

https://github.com/soumith/convnet-benchmarks/blob/master/torch7/imagenet_winners/googlenet.lua

```
ModelType: GoogleNet    Kernels: cudnn  Input shape: 128x3x224x224
cudnn                                   :updateOutput():     451.02
cudnn                                :updateGradInput():     570.26
cudnn                              :accGradParameters():     357.24
cudnn                                          :Forward:     451.02
cudnn                                         :Backward:     927.49
cudnn                                            :TOTAL:    1378.52
```

**Comment by szagoruyko** [comment]
Awesome will make it default for loadcaffe

**Comment by szagoruyko** [comment]
the problem with cudnn ReLU is it can only be applied to 4d tensors so it fails in Linears. Is there a point in adding in-place option to nn.ReLU also?

**Comment by soumith** [comment]
yea, we can. or i can add nD support to cudnn (let me do that now)

**Comment by soumith** [comment]
added nD support for cudnn.ReLU in trunk

**Comment by szagoruyko** [comment]
great, loadcaffe with cudnn now does all ReLU activations in-place.

**Pull request merged**
