### PR TITLE
[fix] errcheck is undeclared 

### PR DESCRIPTION
**Pull request by iamalbert**
Thanks for this amazing project. just to fix a tiny slip of the pen.

`errcheck` is not bound to correct function in `cudnn`
https://github.com/soumith/cudnn.torch/blob/master/init.lua#L25

### CODE REVIEW

**Comment by fmassa** [comment]
Hum, interesting. Except if I'm missing something, this has been around since R2.
Not sure this fixes it though, [as `errcheck` is only defined a few lines below in the same file](https://github.com/soumith/cudnn.torch/blob/master/init.lua#L52-L61)

**Comment by iamalbert** [comment]
run a tiny test with `th -g`
```lua
require 'cudnn'

local m = cudnn.RNN(2,2,1)
local i = torch.rand(3,3, 2):cuda()

local o = m:forward(i)
print(o)
```

you can see the following warning
```
atempt to read undeclared variable: errcheck @ /home/xxx/torch/install/share/lua/5.1/cudnn/init.lua:25
```

**Comment by fmassa** [comment]
@iamalbert I agree that there is a problem here. But I'm not sure that your fix is enough though (for the reason I mentioned in the beginning). I'm wondering if it's not better to just move the `errcheck` definition to the top of the file

**Comment by soumith** [comment]
i think it's fine. the gc will not be called on handle before the errcheck function gets defined.

**Pull request merged**
