### PR TITLE
add test for Tanh and Sigmoid inplace

### PR DESCRIPTION
**Pull request by edgarriba**
includes test for Tanh and Sigmoid activations using inplace mode

### CODE REVIEW

**Comment by soumith** [comment]
tanh and sigmoid cant be done in-place right?

**Comment by ngimel** [comment]
Yes. I assume the tests are passing?

**Comment by edgarriba** [comment]
@soumith don't you have automatic tests checker for PR?

**Comment by soumith** [comment]
no we dont have gpu builds for this repo

**Comment by ngimel** [comment]
Hmm, the I/O tests are failing on my machine (regular ones are passing, as they should, because cudnn supports this).

**Comment by ngimel** [comment]
I/O tests are failing because testIO does not clone input, and for inplace layers it is overwritten
https://github.com/torch/nn/blob/master/Jacobian.lua#L292
so the second time the layer is run with the different input. 
The reason ReLU is passing is because ReLU(input) = ReLU(ReLU(input))
@soumith, should this be fixed in Jacobian?

**Comment by soumith** [comment]
ohh. yea, fixing Jacobian seems appropriate.

**Pull request closed without merging**
