### PR TITLE
Add cudnn.externalizeString

### PR DESCRIPTION
**Pull request by albanD**
This solves #246 

I am not very familiar with this repo's conventions so please let me know if this function should be placed somewhere else.

Also, @soumith it may be needed to look with the nvidia guys which functions from cudnn will actually modify the string we give them. Otherwise the lua internal strings will be modified leading to possibly very hard to track bugs.

### CODE REVIEW

**Comment by soumith** [comment]
there's so much wtf here. If you see the cudnn C API, the stuff that's actually passed in is an enum, and not a string https://github.com/soumith/cudnn.torch/blob/master/ffi.lua#L58-L63

the automatic conversion over from Lua / LuaJIT ffi into enum is giving problems maybe....
Or maybe strings are never supposed to be passed but just worked out accidentally uptil now...

**Comment by soumith** [comment]
thanks for the PR btw!

**Comment by albanD** [comment]
Notes on the enum and the ffi:

```lua
local format = ffi.new("cudnnTensorFormat_t[1]") -- ffi initialize memory with 0s
print(format[0]) -- Outputs 0
format[0] = "CUDNN_TENSOR_NHWC"
print(format[0]) -- Outputs 1
print(format[0] == "CUDNN_TENSOR_NCHW") -- Outputs false
print(format[0] == "CUDNN_TENSOR_NHWC") -- Outputs true
format[0] = "foo" -- Raise error: unable to convert string to enum
print(format[0] == "foo") -- Outputs false
```

The current version where we give strings directly does not allow for return values (and leads to very bad behavior if the C side tries to modify it). For the cudnn functions that actually requires to return elements from enum, we can do something like the following:
```lua
local format = ffi.new("cudnnTensorFormat_t[1]") -- Create a new enum element
print(format[0]) -- Outputs 0

-- Call cudnn function that would modify the enum to the value 1
errcheck('myCudnnFunction', format)

print(format[0]) -- Outputs 1
```

**Comment by ngimel** [comment]
I've submitted a PR with what @albanD suggested in a previous comment to fix #246. @soumith, strings can be passed as enums in luajit ffi, see section on "Conversions from Lua objects to C types" here http://luajit.org/ext_ffi_semantics.html, but apparently they should not be passed for output arguments. I'll fix cudnn docs for cudnnGetFilterNdDescriptor to indicate that datatype, format, nbDims and filterDimA are actually output rather than input args.

**Pull request merged**
