### PR TITLE
Natalia fix corner case where both reference impl and cudnn produce nans

### PR DESCRIPTION
**Pull request by borisfom**

### CODE REVIEW

**Comment by soumith** [comment]
cc: @colesbury reference implementation produces nans?
Also, rather than disable the test, shouldn't we fix the corner case?

**Comment by ngimel** [comment]
It is a totally degenerate case, where averaging is done over a dataset of size 1. The expected output for this case is a tensor filled with 0's, so your training will stop right there and this case should never ever be encountered in practice. One can argue how variance and unbiased variance should be calculated. As it stands in both implementations now, unbiased variance is divided by (N-1), producing nans.

**Comment by colesbury** [comment]
Should we trigger an error or something on batch size 1 then instead of NaNs?

**Comment by ngimel** [comment]
We can fix cudnn to return CUDNN_STATUS_BAD_PARAM.

**Pull request merged**
