### PR TITLE
WIP: variable length sequences for RNNs

### PR DESCRIPTION
**Pull request by killeent**
Analogous to https://github.com/pytorch/pytorch/pull/873

- Pass variable length sequences to RNN forward/backward passes
- Utility functions to handle padded and packed sequences of this nature

### CODE REVIEW

**Comment by killeent** [comment]
@ngimel can you possibly explain the expectation for the Tensor descriptors for a variable length sequence? e.g. Suppose we have a packed tensor of 7 entries, with batch_size_per_timestep of `[7, 7, 5, 5, 3, 3, 1]`. Then our packed tensor is of size `31 x inputSize`. My understanding is that we should have 7 descriptors in our input descriptor array, with sizes/strides:

- size(7, inputSize, 1), stride(inputSize, 1, 1)
- size(7, inputSize, 1), stride(inputSize, 1, 1)
- size(5, inputSize, 1), stride(inputSize, 1, 1)
- size(5, inputSize, 1), stride(inputSize, 1, 1)
- size(3, inputSize, 1), stride(inputSize, 1, 1)
- size(3, inputSize, 1), stride(inputSize, 1, 1)
- size(1, inputSize, 1), stride(inputSize, 1, 1)

is this correct?

**Comment by ngimel** [comment]
Yes, that's correct. To restate, in this case your batch consists of 2 samples of length 2, 2 samples of length 4, 2 samples of length 6 and 1 sample of length 7, you are packing them in sequence-first order, and your descriptors are as you stated. Make sure that the batch size (first dimension in the descriptor) is sorted in decreasing order, as is listed in your example.

**Comment by killeent** [comment]
@ngimel thanks! What is the expected output descriptor for this? I would expect something like 7 descriptors, each with the appropriate batch_size_per_timestep as the first dim, but I am less clear on the others, e.g.:

- size(7, some function of input size, hidden size, #directions, etc., ?)
- size(7, ?, ?)
- size(7, ?, ?)
- size(7, ?, ?)
- size(7, ?, ?)
- size(7, ?, ?)
- size(5, inputSize, 1)
- size(5, inputSize, 1)
- size(3, inputSize, 1)
- size(3, inputSize, 1)
- size(1, inputSize, 1)

**Comment by ngimel** [comment]
From the manual:
An array of fully packed tensor descriptors describing the output
from each recurrent iteration (one descriptor per iteration).
The second dimension of the tensor depends on the direction
argument passed to the cudnnSetRNNDescriptor call used to
initialize rnnDesc :
‣
If direction is CUDNN_UNIDIRECTIONAL the second
dimension should match the hiddenSize argument passed to
cudnnSetRNNDescriptor .

‣
If direction is CUDNN_BIDIRECTIONAL the second dimension
should match double the hiddenSize argument passed to
cudnnSetRNNDescriptor .
The first dimension of the tensor n must match the first dimension
of the tensor n in xDesc.

So, for unidirectional, output descriptors are same as input with inputSize replaced by hiddenSize, for bidirectional inputSize is replaced by 2*hiddenSize

**Comment by killeent** [comment]
@ngimel Great thanks! One last q - in the existing RNN Unit Testing we compare against some magic numbers from an RNN sample. I'm not sure where these numbers are sourced from, but my guess is that the only real way to test the batched variable length sequences is just to generate some example numbers and verify the outputs etc. In the PyTorch code we make a copy of two LSTMs and pass the batch to one and the individual sequences to the other. What do you think?

**Comment by ngimel** [comment]
Yes, testing in torch is less than ideal, but absent a reference implementation there's not much one can do. Generating numbers in pytorch and comparing torch against them seems like the way to go. Alternatively, you can, say, prepare a batch that consists of sequences of, e.g., 3 lengths, and compare outputs when you are operating on this batch directly, and when you split it into 3 equal sequence length batches - I think pytorch has a test like this for variable sequence length.

**Comment by ngimel** [comment]
Thanks!

**Pull request merged**
