### PR TITLE
clearState for SpatialFullConvolution

### PR DESCRIPTION
**Pull request by szagoruyko**
Not sure how it passed testIO test which calls clearState

### CODE REVIEW

**Comment by soumith** [comment]
could you check why it passed testIO when it shouldn't have?

**Comment by fmassa** [comment]
The reason is when the input is a table, one of the buffers is not properly rebuild. I have a pending fix for that for a while, but I need to ask permission before pushing it.

**Comment by fmassa** [comment]
Oh, wait, this is cudnn. I was talking about nn. Sorry about that

**Comment by sniklaus** [comment]
May somebody have a look at #313 and check whether my finding / understanding is correct? Thanks!

**Pull request merged**
